# shelf, title, blurb, status
# shelf, title, blurb, status
# shelf, title, blurb, status
BOOKS=[
(1,'Area',"Nuna's area is d&#178;, the square of its own width.",'Compiled'),
(1,'Perimeter','3&#960;r &#8212; six quarter-circle arcs of one radius, and nothing else.','Draft'),
(1,'Height','r(2+3&#8730;2)/2, about 3.1213r, read off the four-circle construction.','Draft'),
(1,'Width','2r, which is also d, the diameter of the founding circle.','Draft'),
(1,"The diamond's area",'(4&#8722;&#960;)r&#178;, the sum of four quarter-circle offcuts.','Draft'),
(1,'Lattice spacing','Adjacent lattice points sit exactly r&#8730;2 apart.','Draft'),
(1,'The parity rule','A lattice point is a circle when i+j is even, a diamond when odd.','Contested'),
(1,'The tiling-count match','Domino-tiling counts on the lattice reproduce OEIS A004003.','Draft'),
(1,'The 1,157','Sixteen arrangements, one exclusion rule, exactly 1,157 legal combinations.','Verified'),
(1,'717 connected shapes','Of the 1,157, exactly 717 fuse into a single connected shape.','Draft'),
(1,'The counting law','Q &#8722; O = 4 &#8722; k. Under four pieces leaves quarter-discs nothing absorbs.','Draft'),
(1,'The wave is the silhouette',"The board's wave line and any arrangement's outer edge are one curve.",'Draft'),
(1,'The construction','Four equal circles tangent in a square; one kept whole, the void kept, one line erased.','Open'),
(1,'Symmetry','One mirror axis, no rotational symmetry, therefore four orientations.','Open'),
(1,'The tile is a domino','Every placement covers exactly one circle cell and one diamond cell.','Open'),
(1,'The isoperimetric ratio','A/P&#178; = 4/(9&#960;&#178;) &#8212; about 57% of what a circle of equal perimeter holds.','Open'),
(2,'The cousins','507 placements reducing to 73 canonical shapes, sorted by corners returned.','Shelved'),
(2,'The combination-shape families','317 families under D&#8324;, and why the reference says 362.','Shelved'),
(2,'The three forms','A grid with a line erased, a circle cut from a square, a run of waves.','Shelved'),
(2,'Parity and the board','Why tile-count parity, not skill, decides whether a game can end drawn.','Shelved'),
(2,'Company without pairs','20 of 36 companions only ever appear in threes or more.','Shelved'),
(2,'Nuna-shaped pixels','The case for a rendering lattice built on this tile instead of the square.','Speculative'),
(2,'Graph-colouring connections','Whether the exclusion rule is a face of something more general.','Speculative'),
(2,'Six-tile groupings','The design space past k = 6, still without a tool to sift it.','Open'),
(2,'Tessellation, classified','Which combination-shape families actually tile the plane.','Open'),
(2,'The holes','The shapes that cannot close, and what they say about the ones that can.','Open'),
(3,'The 1,157, in full','Every legal 16-point combination, drawn, on one plate.','Planned'),
(3,'The combination-shape dataset','All 317 families as a browsable plate rather than a working file.','Planned'),
(3,'The cousin dataset','73 families and their relations, complete.','Planned'),
(3,'Pairs and beyond','The companion catalogue, from pairs up through thirteen-shape sets.','Planned'),
(3,'A New Shape, original plates',"The source book's own proofs and diagrams, preserved as drawn.",'Planned'),
(3,'The 24-point badge','Reserved. Empty until the enumerator returns a count worth trusting.','Reserved'),
(4,'The 16-point badge model','28 Jul. The first model. Four rebuilds before the docking geometry was right.','Archived'),
(4,'The badge shapes','30 Jul. Exact-arc silhouettes, both badges; a missing B&#8211;X exclusion found and fixed.','Archived'),
(4,'The frame sketch','30 Jul. Superseded. Where the two-round-two-sharp corner claim was tested and failed.','Superseded'),
(4,'The first plates',"1 Aug. How it's made, area, circumference, compiled, plus the 3D tile mesh.",'Archived'),
(4,'The board instrument','4 Aug. Size slider, orientation toggle, wave overlay, SVG export.','Archived'),
(4,'The enumerator kernel','10 Aug. Two counting engines cross-checked. 69 tests.','Archived'),
(4,'The gold logo lab','18 Aug. Superseded. The wave-as-snake direction, before the ambigram.','Superseded'),
(4,'The game simulator','22 Aug. The dashboard everything else forked from.','Archived'),
(4,'The pattern generator','23 Aug. Groupings pack and the two-tone index.','Built'),
(4,'Green','23 Aug. Dice from the di-nuna polyforms, printable nets, tumbling die.','Scoped'),
(4,'Black','29 Aug. The flagship territory game.','Built'),
(4,'The cousins catalogue','6 Sep. Reference, poster, pattern tool, batch-one model.','Built'),
(4,'The ambigram tool','6 Sep. Fourteen versions to the wordmark.','Superseded'),
(4,'The ribbon wordmark','7 Sep. The junction resolved as a fold. Asset kit.','Built'),
(4,'Red','7 Sep. Circular, then spherical, then a pole-to-pole race.','Built'),
(4,'White','8 Sep. The paint board, the embed, the 317-family dataset.','Built'),
(4,'Blue','11 Sep. Deep Water, the style labs, the seven-beat choreography.','Built'),
(4,'Stacker','12 Sep. Custom rigid-body physics on a wave-profile base.','Built'),
(4,'The puzzle','Scoped. Bring a photograph, choose a pattern, cut it and rebuild it.','Scoped'),
(5,'Pavers','The shape cast at walking scale: mould, draft angle, tolerance, weight.','Draft'),
(5,'Brick','The shape at masonry scale, and what a course of it does to a wall.','Draft'),
(5,'Tile','Ceramic and wall work &#8212; ancestor of the gallery photographs.','Draft'),
(5,'Linoleum and sheet flooring','Printed and inlaid, where the repeat is cut rather than laid.','Draft'),
(5,'Interlocking laminate','A click-lock profile that still leaves all four orientations reachable.','Open'),
(5,'Edges and transitions','Border and threshold pieces, and planning a floor as a bounded room.','Open'),
(5,'Textile','Weave and print, where the repeat has to survive being folded.','Draft'),
(5,'Wallpaper','Repeat patterns fitted to a wall, and to specific arrangements.','Draft'),
(5,'Interior mockups','Rooms with the shape inhabited rather than merely patterned.','Draft'),
(5,'The physical board','How Black becomes an object: material, fabrication, components.','Draft'),
(5,'Where it already was','Instances found rather than made. Ornament, paving, textile that turns out to be this.','Open'),
(6,'Origins','How the shape was first noticed, before there was any maths for why it worked.','Draft'),
(6,'Why &#8220;nuna&#8221;',"Reserved. The name's own story.",'Reserved'),
(6,'A New Shape, revisited','The relationship to the original book now, and what has moved since.','Draft'),
(6,'The parity bug','The morning something long trusted turned out to be wrong.','Draft'),
(6,'First match','The moment a count first landed on the number it was supposed to.','Draft'),
(6,"What didn't survive",'Constructions and explanations that were tried and let go.','Draft'),
(6,'On depth as the real protection','Why the choice was openness and originship rather than enforcement.','Draft'),
(6,'Where it goes','What a world with this shape in it looks like, written forward.','Open'),
]
SHELVES=[
 (1,"Introduction","Core claims","Book One. One atomic, checkable fact per page &#8212; read straight through, or entered at any single claim."),
 (2,"Shelf two","Explorations and theory","The work too large to state in a sentence."),
 (3,"Shelf three","Datasets","Plates and catalogues held whole rather than described."),
 (4,"Shelf four","Models and tools","Every model built, in order, including the ones that were replaced. Each entry is also a live tab."),
 (5,"Shelf five","Physical world","The shape out in the world, at the scale of a room."),
 (6,"Shelf six","Personal writing","Sixty-four marks, every one of them maximal."),
]
